### ISSUE TITLE
Support for Rollup 3

### ISSUE THREAD

**Issue by shirblc** [rollup/stream#17]
- @rollup/stream Version: 2.0.0

### Feature Use Case

Rollup 3 was just released last week, so this would be useful for developers who want to use the new version.

### Feature Proposal

The current version of rollup/stream requires rollup 2.x as a peer dependency, but now that rollup 3 has been released, it would be useful to have a version of rollup/stream that supports it. The current version might still work with rollup 3 (I haven't tried it, so I'm not sure), but it might also have unintended consequences (especially with some of the deprecated/removed config/plugin options in rollup 3). 

I realise it might be early days and you haven't had the chance to update the package yet, but I'd love to know if there are plans to support rollup 3 soon. I'd be happy to help testing/updating (if necessary) the package with rollup 3 if you want/need.

Thank you!

**Comment by lukastaegert** [comment]
Fix at #18

**Comment by shirblc** [comment]
Brilliant, thank you!
