### ISSUE TITLE
Any plans to update this for compatibility with Rollup 2.x?

### ISSUE THREAD

**Issue by wearhere** [rollup/stream#7]
- @rollup/stream Version: 0.1.0

### Feature Use Case

Developers who want to use the latest Rollup.

### Feature Proposal

Update this for support with the latest Rollup (am I using this template right? 😅).

I don't know for sure that this _isn't_ compatible with the latest Rollup, but I do note that Rollup 2.x violates this package's [peer dependencies](https://github.com/rollup/stream/blob/0b06ba1b6c208a30bffa7d549867700c0e5e2c2f/package.json#L44).

Hopefully context on this might be fresh given that this package is only 3 months old itself.

**Comment by yairEO** [comment]
plase maintainers, assist

**Comment by shellscape** [comment]
ea2d275
