### ISSUE TITLE
NPM Package out of date?

### ISSUE THREAD

**Issue by natwallbank** [rollup/stream#8]
- @rollup/stream Version: 1.0.0
- Rollup Version: 2.18.0
- Operating System (or Browser): Windows 10
- Node Version: 12.14.1

### How Do We Reproduce?

Run a rollup build using this plugin, with plugins specified in the Rollup config, e.g.

```
plugins: [
      rollupResolve(),
      rollupBabel({
        exclude: 'node_modules/**',
        presets: [
          ['@babel/preset-env', {modules: false}],
          ['@babel/preset-react', {modules: false, development: isDev}]
        ],
        plugins: ['@babel/plugin-proposal-class-properties'],
        babelHelpers: 'bundled'
      }),
      commonJs({
        include: 'node_modules/**',
        ignore: ['conditional-runtime-dependency']
      })
    ]
```

It builds correctly, but lots of errors appear like the following:

```
The "buildStart" hook used by the output plugin node-resolve is a build time hook and will not be run for that plugin. Either this plugin cannot be used as an output plugin, or it should have an option to configure it as an output plugin.
```

### Expected Behavior

These errors shouldn't appear.

### Actual Behavior

As above.

### Hypothesis

The NPM package doesn't appear to match the code shown here: https://github.com/rollup/stream/blob/master/src/index.ts

Specifically, in the version in my local node_modules folder I see the following line:

```
const { output } = await bundle.generate(options);
```

If I change it to match the version hosted here (by only supplying the output options) it works correctly:

```
const { output } = await bundle.generate(options.output);
```

**Comment by htshah** [comment]
Facing the same issue.

**Comment by shellscape** [comment]
This issue wasn't taken up by maintainers because it didn't include a valid reproduction. If still an issue, we'd be happy to review a PR from the community to resolve the issue.
